"""Authenticated deterministic cost forecasting routes."""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, Request

from app.auth.dependencies import get_current_active_user
from app.auth.models import User
from app.core.cache import RedisCache, get_cache
from app.core.rate_limit import enforce_cost_rate_limit
from app.schemas.forecast import ForecastQuery, ForecastResponse
from app.services.forecasting import ForecastingService

router = APIRouter(prefix="/forecast", tags=["forecast"])


def get_forecasting_service(
    current_user: Annotated[User, Depends(get_current_active_user)],
    cache: Annotated[RedisCache, Depends(get_cache)],
) -> ForecastingService:
    """Build a forecast service scoped to the authenticated user."""
    return ForecastingService(cache=cache, user_scope=str(current_user.id))


@router.get(
    "",
    response_model=ForecastResponse,
    summary="Forecast future normalized cloud spend",
    description=(
        "Produce a deterministic 7, 14, or 30-day forecast from normalized historical "
        "Cost Explorer data. Forecast values are never generated by an LLM."
    ),
)
@enforce_cost_rate_limit
async def get_forecast(
    request: Request,
    query: Annotated[ForecastQuery, Depends()],
    service: Annotated[ForecastingService, Depends(get_forecasting_service)],
) -> ForecastResponse:
    """Return a cached or freshly calculated deterministic forecast."""
    return await service.forecast(query)
