"""create initial schema

Revision ID: 92b5be269a7b
Revises:
Create Date: 2026-06-27 20:20:29.753695+00:00
"""

from collections.abc import Sequence

revision: str = "92b5be269a7b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
